### ISSUE TITLE
Privacy provider syntax error

### ISSUE THREAD

**Issue by micaherne** [PlaneteStream/moodle-tinymce_planetestream#2]
The code for version 6.52, which is released on the Moodle plugin database, doesn't seem to have made it onto here yet, but it has the same issue as the atto plugin (https://github.com/PlaneteStream/moodle-atto_planetestream/issues/6)

The privacy provider file isn't valid PHP syntax. It causes the Moodle unit test core_privacy\manager_test::test_installed_plugins to fail.

**Comment by PlaneteStream** [comment]
Thanks for the report, this should be resolved now and up-to-date with the repo.
