### ISSUE TITLE
When will the release for Moodle 4.2 be available?

### ISSUE THREAD

**Issue by tsigmu36** [PlaneteStream/moodle-tinymce_planetestream#3]
Moodle has introduced a new version of TinyMCE as the standard editor with Moodle 4.2 (see release notes https://moodledev.io/general/releases/4.2) and has remove the legacy on which was installed under `lib/editor/tinymce`.
The new installation path is `lib/editor/tiny` and therefore the plugin will not work with Moodle 4.2, as it extends among other things `class editor_tinymce_plugin`.

Are you planning to release an update soon? If yes, when will it be available?

Regards,
Thorsten

**Comment by PlaneteStream** [comment]
Hi Thorsten,

We're currently working on the new version of the plugin for Moodle 4.1 onwards and are hoping to release this some time in August. In the meantime, the ATTO plugin will continue to work in its respective editor in recent versions of Moodle.

Thanks,
eStream
