### ISSUE TITLE
Is there an update for Moodle 4.4?

### ISSUE THREAD

**Issue by neeesn** [PlaneteStream/moodle-tinymce_planetestream#4]
We have some clients which are using Moodle and planet Estream and we are currently updating their moodle to 4.4 version and tiny pro. Is there a update ready? (same for the atto editor need a 4.4 version)

**Comment by PlaneteStream** [comment]
Hi there, 

Sorry for the delay, I've replied in a direct email but there is a new repo for this plugin located here:

https://github.com/PlaneteStream/moodle-tiny_estream
